CREATE DATABASE IF NOT EXISTS trouve_ton_artisan CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE trouve_ton_artisan;
CREATE TABLE categories(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(100) NOT NULL UNIQUE);
CREATE TABLE specialties(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(120) NOT NULL,category_id INT NOT NULL,CONSTRAINT fk_specialties_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE RESTRICT ON UPDATE CASCADE,UNIQUE KEY uk_specialty_name_per_category(name,category_id));
CREATE TABLE artisans(id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(150) NOT NULL,rating TINYINT UNSIGNED NOT NULL DEFAULT 0,locality VARCHAR(150) NOT NULL,specialty_id INT NOT NULL,website VARCHAR(255),picture_url VARCHAR(255),about TEXT,email VARCHAR(190) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,CONSTRAINT fk_artisans_specialty FOREIGN KEY (specialty_id) REFERENCES specialties(id) ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE TABLE contact_messages(id BIGINT AUTO_INCREMENT PRIMARY KEY,artisan_id INT NOT NULL,sender_name VARCHAR(150) NOT NULL,sender_email VARCHAR(190) NOT NULL,subject VARCHAR(180) NOT NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_messages_artisan FOREIGN KEY (artisan_id) REFERENCES artisans(id) ON DELETE CASCADE);
CREATE INDEX idx_artisans_name ON artisans(name);
CREATE INDEX idx_artisans_locality ON artisans(locality);
