require("dotenv").config();
const express=require("express");
const cors=require("cors");
const helmet=require("helmet");
const rateLimit=require("express-rate-limit");
const api=require("./routes/api");
const app=express();
app.use(helmet());
app.use(cors({origin:process.env.CORS_ORIGIN,credentials:true}));
app.use(express.json({limit:"100kb"}));
app.use(rateLimit({windowMs:15*60*1000,max:200,standardHeaders:true,legacyHeaders:false}));
app.get("/health",(req,res)=>res.json({ok:true}));
app.use("/api",api);
app.use((req,res)=>res.status(404).json({error:"Not found"}));
app.use((err,req,res,next)=>{console.error(err);res.status(500).json({error:"Server error"});});
module.exports=app;
